
target 'SimpleExample' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for GaphViz
  pod "Clibgraphviz", :path => "../"
  pod "GraphViz", :path => "../"


end
